name: Build Development

on:
  push:
    branches: [ "development" ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
      - '.gitattributes'

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !startsWith(github.event.head_commit.message, '[Ci skip]')"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Tests & Build
        run: ./gradlew test build
